import { createSlice } from "@reduxjs/toolkit";

const CartSlice = createSlice({
    name : "cart",
    initialState : {
        items : [],
    },
    reducers : {
        addItem : (state, action) =>{ state.items.push(action.payload) },
        removeItem : (state) => { state.items.pop() },
        clearCart : (state) => { state.items = [] },
    } 
})

// we will export the action and reducer from this slice file, so that we can use it in our components and store respectively


// here we are exporting the action creators which are generated by createSlice for each reducer function we defined 
// in the reducers object, these action creators will be used in our components to dispatch actions to the store
export const { addItem, removeItem, clearCart } = CartSlice.actions;  

// here reducer is like single object which contains all the reducer functions we defined in the reducers object,
//  we will export this reducer to use it in our store
export default CartSlice.reducer;

